### ISSUE TITLE
Create Project > Created Project is not displayed (user role: Project manager) on the projects listing page 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#625] opened 2020-10-26 10:05 UTC
**Describe the bug**
Create Project > Created Project is not displayed (user role: Project manager) on the projects listing page

**Steps to Reproduce**
1. Register user with roles i.e. `ProjectManager` 
2. Login 
3. Click on ` Create New Item` > `Select Project menu` > `Enter project name`
4. Click on the `submit` button
5. View `Project` listing page

**Expected Result**
Created Project should be displayed.

**Actual Result**
Created Project is displayed after refreshing the page.

See video : 
https://drive.google.com/file/d/1J6LRbvviPW_e2owBtdTT4q3eVGiwZOQ7/view?usp=drivesdk

cord-field#  6c0299b7

**Comment by CarsonF** [comment] 2020-10-26 19:48
Duplicate of #547

**Closed by CarsonF** 2020-10-26 19:48 UTC
Labels: bug
