### ISSUE TITLE
Project > Language engagement > Product >  Getting "TypeError: Cannot read property 'canRead' of undefined" error when user click on the edit button of  created product

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#819] opened 2021-04-20 06:01 UTC
**Roles:** All

**Describe the bug**
Project > Language engagement > Product >  Getting `TypeError: Cannot read property 'canRead' of undefined` error when user click on the edit button of  created product

**Steps to Reproduce**
1. Login as an admin user
2. Create a new Project 
3. Add language engagement and click on the `View Details` button 
4. Click on the `Add Product` button and create a new product
5. Click on the `View Details` button of the language engagement
6. Click on the `Edit` button of products

**Expected Result**
Product should be editable

**Actual Result**
Getting `TypeError: Cannot read property 'canRead' of undefined` error when user click on the edit button of  created product

See video - 

https://user-images.githubusercontent.com/5212585/115344312-10767e00-a162-11eb-9c2c-93af51a000f7.mp4

cord-field# 71c8ecb5

**Comment by parashara1** [comment] 2021-04-20 16:49
This bug is not present on the latest master when I try to reproduce it, the "Edit" button of products works and doesn't throw an error and is editable. I was able to successfully reproduce the bug however once I checked into the branch where this bug originates, "71c8ecb". Once I spun up my local front end environment in that branch, the bug in fact exists and I received the same error when trying to click the "Edit" button.

**Comment by parashara1** [comment] 2021-04-20 16:59
@iPiyushPatel the same error of "TypeError Cannot read property 'canRead' of undefined" exists on the "71c8ecb" branch, however the error doesn't exist on latest master. Since the latest master seems to not have this issue, I will be closing it.

**Comment by iPiyushPatel** [comment] 2021-04-21 07:32
Hi, @parashara1 @glassblowerscat @CarsonF @michaelmarshall @ParkeBrown 
I've verified the issue and still replicate this issue on both the latest develop 71c8ecb5 and master 5ab8b76d branch 
See video : 

https://user-images.githubusercontent.com/5212585/115513861-64539680-a238-11eb-96db-305093bc2a95.mp4

**Comment by ParkeBrown** [comment] 2021-04-21 14:21
@parashara1 Can you take one more look?

**Comment by CarsonF** [comment] 2021-04-21 16:21
Duplicate of #821

**Closed** 2021-04-29 16:05 UTC
Labels: bug
