### ISSUE TITLE
Projects > Projects created by "Root Admin" are not displayed for specific user role (i.e. "Intern", "Consultant")

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#640] opened 2020-10-28 12:21 UTC
**Describe the bug**
Projects > Projects created by `Root Admin` are not displayed for specific user role (i.e. `Intern`, `Consultant`)

**Steps to Reproduce**
1. Login to the Root admin
2. Create Project
3. Register user with `Intern` role and log in
4. Register user with `Consultant` role and log in
5. Click on the `Project` menu 

**Expected Result**
Project should be displayed.

**Actual Result**
Projects created by `Root Admin` are not displayed for specific user role (i.e. `Intern`, `Consultant`)
See video -  https://drive.google.com/file/d/1aVVVZxu-7ZJiHHK4zh_m_quoWwdK0v7F/view?usp=drivesdk

cord-field# 29636feb

**Comment by sethmcknight** [comment] 2020-10-28 13:31
@iPiyushPatel it looks like that project is performing as I would expect.

The following roles should only be able to list or view Projects they are assigned to:
- Intern
- Liaison
- Mentor
- Regional Communication Coordinator
- Translator
- Consultant

**Comment by iPiyushPatel** [comment] 2020-10-29 05:32
Hi @sethmcknight 
Thanks for the clarification; however, I've below questions: 

1. I'm not sure how we can assign a project to a user via UI/API? 
2. Currently, a project created by ANY PM role, can be VIEWED by all user roles. Is that expected?

Please suggest if any.
Thanks,

**Comment by elisabeth-sorrell** [comment] 2020-12-31 22:32
@iPiyushPatel This is pretty old, so you may already know this but a user is added to a project in the UI by going to the Projects -> Project Card -> Team members and adding from there.

as far as the second point, it is not expected behavior according to the Schema doc. the list that @sethmcknight gave are for users that should only be able to see that project if they are a member, so I'll go ahead and fix that.

**Comment by iPiyushPatel** [comment] 2021-01-01 13:10
Hi @elisabeth-sorrell 
I have verified on develop 89ee57a1 and it's working as expected for user `Intern` and `Consultant` roles.

but for other user roles project is not displayed in the project listing after login, but It can be found by searching.
1. Create Project by the root user
2. Login as a `RegionalDirector`
3. Search the project created by root user

See Video: https://drive.google.com/file/d/1RPaW79bTcvJuLGvtv6aZtdsVhoe-Lxv1/view?usp=drivesdk

**Comment by elisabeth-sorrell** [comment] 2021-01-02 20:16
@iPiyushPatel for roles that have a global read on project properties, they should be able to see the project. So, logging in with Regional Director role after creating the project by root, it will be listed with the other projects if you turn the `only see my projects` filter off. The below snapshots show the global read permissions of the regional director a project's properties. So, this is expected behavior.

However, if I were to login with the consultant role that is _not_ assigned to the project and do the same thing (turning off the `mine` filter) I can _still_ see the project in the list. That's unexpected behavior because the consultant role should only see the project if it's a project member. I've started working on that, and will hopefully have a PR soon

**Comment by michaelmarshall** [comment] 2021-01-05 19:55
@iPiyushPatel I think we have a bug if non-roled users can see projects they aren't assigned to. Otherwise, the `intern` and `consultant` role should only be able to view projects they are a member of.

So this is also a bug if those roles can see projects they aren't assigned to. I believe @elisabeth-sorrell is making a bug ticket for this.

**Closed** 2021-01-07 16:09 UTC
Labels: bug
