### ISSUE TITLE
Frontend goes to a blank screen when user attempts to add an MOU Start Date

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#766] opened 2021-03-23 15:36 UTC
LogRocket Issue [#29290313](https://app.logrocket.com/x6d22y/cord-prod/issue/29290313)

`TypeErrorCannot read property 'get' of null @date-io/luxon/build/index.esm in getMonth`

```
./node_modules/@date-io/luxon/build/index.esm.js in getMonth on line 181:22
176	    LuxonUtils.prototype.setSeconds = function (value, count) {
177	        return value.set({ second: count });
178	    };
179	    LuxonUtils.prototype.getMonth = function (value) {
180	        // See https://github.com/moment/luxon/blob/master/docs/moment.md#major-functional-differences
181	        return value.get("month") - 1;
182	    };
183	    LuxonUtils.prototype.setMonth = function (value, count) {
184	        return value.set({ month: count + 1 });
185	    };
186	    LuxonUtils.prototype.getYear = function (value) {
./node_modules/@material-ui/pickers/Picker-80c97ed7.js in c on line 592:28
587	      date = _ref.date,
588	      onMonthChange = _ref.onMonthChange,
589	      onChange = _ref.onChange;
590	  var utils = useUtils();
591	  var classes = useStyles$1();
592	  var currentMonth = utils.getMonth(date);
593	
594	  var shouldDisableMonth = function shouldDisableMonth(month) {
595	    var now = utils.date();
596	    var utilMinDate = utils.date(minDate);
597	    var utilMaxDate = utils.date(maxDate);
```

**Comment by CarsonF** [comment] 2021-04-02 07:09
Duplicate of #513

**Closed** 2021-04-03 00:56 UTC
Labels: bug
