### ISSUE TITLE
Move East Slovak Romani 3 Project to Next Stage in Pipeline

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#736] opened 2021-02-25 19:37 UTC
Team member needs project moved to next stage in the pipeline.

Field Staff:
The East Slovak Romani 3 project is in the Pipeline. Earlier today I received the consultant's (a non Seed Co consultant) endorsement so I wanted to move this to the next stage in the Pipeline. When I did so I received the following error message below. My Supervisor, Matt Merritt who is Eurasia Regional Director, got the same message and was also unable to move this along in the Pipeline. Can you please correct this as soon as possible? I'm working on this transition now and this needs to be approved within the month. Thanks,

**Comment by blakekrammes** [comment] 2021-02-25 19:46
There's a bug here in the data. Looks like a migration problem. Looking into it.

**Comment by ParkeBrown** [comment] 2021-02-25 19:47
Yes, I believe Seth said we already have a fix for this system wide in the backlog. This is a data fix in the meantime.

**Comment by blakekrammes** [comment] 2021-02-25 19:49
I think this might be something he's not aware of. It's data that wasn't in V2 and so I deleted the place where it's held in V3. Now the API is trying to find that node in the DB and can't so it gives an error. I wasn't aware of that ramification.

**Comment by blakekrammes** [comment] 2021-02-25 22:59
This issue should be fixed now if the team member wants to try updating the status again.

**Comment by sethmcknight** [comment] 2021-02-25 23:09
Confirmed, thanks @blakekrammes

**Closed by sethmcknight** 2021-02-25 23:09 UTC
