### ISSUE TITLE
Languages > Edit > `Provisional Code` and `Ethnologue Code` textbox throw a validation messages for the valid inputs

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#502] opened 2020-09-22 08:56 UTC
**Describe the bug**
Languages > Edit > `Provisional Code` and `Ethnologue Code` textbox throw a validation messages for the valid inputs.

**Steps to Reproduce**
1. Login
2. Click on the languages menu and select language 
3. Click on the edit icon 
4. Hit the `Submit` button without editing any text field

**Expected Result**
Validation messages should not appear for the valid inputs to the `Provisional Code` and `Ethnologue Code` fields.

**Actual Result**
`Provisional Code` and `Ethnologue Code` textbox throw a validation message for the valid inputs.
See video-  https://drive.google.com/file/d/1a2Z4rZbvt_uJgCApXlr2pgo-WsyBr7O4/view?usp=sharing

cord-field# b1ebad03

**Comment by CarsonF** [comment] 2020-09-22 17:31
I cannot reproduce this

**Comment by CarsonF** [comment] 2020-10-13 17:35
@iPiyushPatel can you check and see if this is still happening with latest code?

**Comment by iPiyushPatel** [comment] 2020-10-14 06:21
@CarsonF 
I can still replicate the same on the latest master d4d7b202.
See video: https://drive.google.com/file/d/1FCXgq3GqTbWgrOXBAy8in5y7PvtSwx07/view?usp=drivesdk

**Comment by iPiyushPatel** [comment] 2021-05-11 10:10
Hi @ParkeBrown 
I have still replicated the issue on the latest develop 1d6e8100 
Please find the reference video.
Re-opening the bug
Thanks! 

See video: 

https://user-images.githubusercontent.com/5212585/117798889-32e64d80-b26f-11eb-9a0a-eff1edaefc00.mp4

**Comment by parashara1** [comment] 2021-05-11 14:42
Reproduced bug successfully. The "Provisional Code" & "Ethnologue Code" are failing to validate the inputs in the textbox.

**Comment by daniel-leod** [comment] 2022-06-08 18:14
The only way to reproduce this is by editing an `Ethnologue` whose provisional code and/or code are longer than 3 characters. Since the UI restricts the creation of these objects with said characteristics we're safe to close this issue.

**Closed by daniel-leod** 2022-06-08 18:14 UTC
Labels: bug, reproduced

**Comment by daniel-leod** [comment] 2022-06-08 18:19
@CarsonF Sure
