### ISSUE TITLE
Project > Filter > Blank screen displayed when applying "In development" and "Low" filters

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#503] opened 2020-09-22 09:45 UTC
**Describe the bug**
Project > Filter > Blank screen displayed when applying `In development` and `Low` filters.

**Steps to Reproduce**
1. Login
2. Click on the projects menu and Click on `filter option` button
3. Apply  `In development` and `Low` filter and select `Apply Filter` button 
4. Direct hit the `Submit` button without editing any detail

**Expected Result**
Project results should be displayed according to applied filters.

**Actual Result**
Blank screen displayed when applying `In development` and `Low` filters.
See video-  https://drive.google.com/file/d/1KUQQZNqylrMZAtsm25XAE8Lt4nVdhCri/view?usp=sharing

cord-field# b1ebad03

**Comment by CarsonF** [comment] 2020-09-22 17:26
Duplicate of #488

**Closed** 2020-09-22 17:27 UTC
Labels: duplicate
