### ISSUE TITLE
Project > Goals > "Steps" are not available for "Visual- other" methodology type 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#991] opened 2021-10-29 14:01 UTC
**Roles:** All

**Describe the bug**
Project > Goals > `Steps` are not available for `Visual- other` methodology type 

**Steps to Reproduce**
1.  Login as a root user
2.  Create a project and open a project detail page
3.  Add `LanguageEngagement` and click on the `View Details`
4.  Click on the `Add Goal` button and click on the `methodology` dropdown
5.  Select `Visual - Other` methodology

**Expected Result**
`Steps` should be displayed for `Visual- other` methodology type 

**Actual Result**
 `Steps` are not available for `Visual- other` methodology type 

See video - 

https://user-images.githubusercontent.com/5212585/139448000-cb48bc6f-c108-4deb-8862-64b35c07415d.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 34dbf41

**Comment by daniel-leod** [comment] 2021-11-15 16:50
Duplicate of https://github.com/SeedCompany/cord-api-v3/issues/2240

**Closed by daniel-leod** 2021-11-15 16:50 UTC
Labels: bug

**Comment by iPiyushPatel** [comment] 2021-11-16 06:50
Hi @daniel-leod @CarsonF
I've verified on the latest develop 'afede2f'  and it's working fine for me the `steps` are displayed for the 'Visual-other ' Methodology Type.  Attaching a video for a reference. Thanks!

https://user-images.githubusercontent.com/5212585/141934894-7f99ba3a-7a53-44d7-b540-fd92c87bb737.mp4
