### ISSUE TITLE
Languages > Pagination is not available for more than 25 records

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#500] opened 2020-09-22 08:52 UTC
**Describe the bug**
Languages > Pagination is not available for more than 25 records

**Steps to Reproduce**
1. Login
2. Click on `create a new menu item`  button  and select `language` 
3. Enter mandatory field data and click on the `Submit` button (Language will be created)
4. Repeat Step 2 & 3 for more than 25 time

**Expected Result**
Pagination should be available for more than 25 records

**Actual Result**
Languages >Pagination is not available for more than 25 records
See video -  https://drive.google.com/file/d/10IEQwkx_m3rZ4EYzjVeaQ2lZSa7A7Zgx/view?usp=sharing

**Note**: I found the same issue for Project and Partner.

cord-field# b1ebad03

**Comment by CarsonF** [comment] 2020-09-22 17:35
Yes we haven't handled pagination yet. Duplicate of #95

**Closed by CarsonF** 2020-09-22 17:35 UTC
