### ISSUE TITLE
fields required for periodic reports Domo API

### ISSUE THREAD

**Issue by kjones140** [SeedCompany/cord-field#890] opened 2021-07-13 17:22 UTC
### Periodic Reports API

- DeptID - integer
- FiscalYear - integer
- ProjectType (values 'Translation' or 'Internship') – text  

- Q1NarrativeDueDate thru Q4NarrativeDueDate - date
- Q1NarrativeRcvdDate thru Q4NarrativeRcvdDate – date 
- Q1NarrativeUploadDate thru Q4NarrativeUploadDate – date

- Q1FinancialDueDate thru Q4FinancialDueDate - date
- Q1FinancialRcvdDate thru Q4FinancialRcvdDate - date
- Q1FinancialUploadDate thru Q4FinancialUploadDate – date

- M1FinancialDueDate thru M12FinancialDueDate - date
- M1FinancialRcvdDate thru M12FinancialRcvdDate - date
- M1FinancialUploadDate thru M12FinancialUploadDate – date

- LastSynced - datetime
- CordURL - text

**Comment by sethmcknight** [comment] 2021-07-13 17:57
Closing, duplicate of https://github.com/SeedCompany/seed-api/issues/133

Moved the data over.

**Closed by sethmcknight** 2021-07-13 17:57 UTC
