### ISSUE TITLE
SerachBar > Searching functionality is not working while "Upload Manager" popup is open

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#732] opened 2021-02-22 07:31 UTC
**Roles:** All

**Describe the bug**
SerachBar > Searching functionality is not working while the `Upload Manager` popup is open

**Steps to Reproduce**
1. Login with admin user
2. Create a new project
3. Click on the `Upload file` button
4. Upload the file
5. Click on the search bar and search any project

**Expected Result**
Searching functionality is not working while the `Upload Manager` popup is open

**Actual Result**
Searching functionality should be working while the `Upload Manager` popup is open
See video - 

https://user-images.githubusercontent.com/5212585/108676083-b2d10700-750d-11eb-919b-2fe027738779.mp4

 cord-field# 9fa4b368

**Comment by CarsonF** [comment] 2021-02-22 14:43
Duplicate of #635

**Comment by ParkeBrown** [comment] 2021-02-22 15:40
Noted in 635 and closing

**Closed by ParkeBrown** 2021-02-22 15:40 UTC
