### ISSUE TITLE
BUG | Filtering by 2 Sensitivities (i.e. High & Low) breaks filters

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#528] opened 2020-09-29 21:42 UTC
<img width="1552" alt="Screen Shot 2020-09-29 at 4 42 19 PM" src="https://user-images.githubusercontent.com/7377802/94619684-e9626880-0272-11eb-89a4-e46e71d65139.png">

**Comment by glassblowerscat** [comment] 2020-10-01 22:35
This is a duplicate of #488, and it's actually any use of the Sensitivity filters that crashes the app

**Closed** 2021-01-28 18:23 UTC
Labels: bug
