### ISSUE TITLE
Project > Language Engagement > Product > Getting "Product selection required" error even product type is selected

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#849] opened 2021-05-17 12:51 UTC
**Roles:** All

**Describe the bug**
Project > Language Engagement > Product > Getting `Product selection required` error even product type is selected

**Steps to Reproduce**
1. Login as a Project Manager
2. Create a new Project and go to the project details page
4. Create a language engagement
5. Click on the `View details` button
6. Click on an `Add product` button
7. Select `Scripture` product

**Expected Result**
The error message should not be displayed while the product type is selected

**Actual Result**
Getting `Product selection required` error even product type is selected

See video - 

https://user-images.githubusercontent.com/5212585/118490868-0da88200-b73c-11eb-9592-d6b765be6d00.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 1d6e8100

**Comment by parashara1** [comment] 2021-05-18 10:06
Project Manager gets "Product selection required" error despite the product type being selected already.

**Comment by ParkeBrown** [comment] 2021-05-18 16:27
@sethmcknight we should probably evaluate priority for this when you get back

**Comment by CarsonF** [comment] 2021-08-03 03:28
Duplicate of #907

**Closed by CarsonF** 2021-08-03 03:28 UTC
Labels: reproduced
