### ISSUE TITLE
[BUG] Department ID Could Not be Set

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#630] opened 2020-10-27 16:07 UTC
When submitting a Project with a valid Primary Location for Finance Confirmation, I received an error that the Department ID could not be set.

We need to ensure that:

1) A project with a valid Primary Location assigned always receives a valid Department ID when submitted for Finance Confirmation.
2) A project without a valid Primary Location cannot be submitted for Finance Confirmation.
3) The Department ID is displayed when set.

**Comment by CarsonF** [comment] 2020-10-27 16:54
The problem is the `fundingAccount` on `Location` is optional. So since that is missing the department ID cannot be calculated. Not sure the best process going forward. Only allow locations to be assigned to the `Project.primaryLocation` if they have a funding account?

**Comment by sethmcknight** [comment] 2020-10-27 19:40
@CarsonF yes I think that makes sense. Have we not migrated the funding accounts with Locations?

**Comment by CarsonF** [comment] 2020-10-28 15:25
> Have we not migrated the funding accounts with Locations?

Question for @michaelmarshall @blakekrammes

**Comment by blakekrammes** [comment] 2020-10-28 15:26
Yes.

**Comment by frankyma** [comment] 2020-11-04 23:47
Duplicate of https://github.com/SeedCompany/cord-api-v3/issues/1499

**Closed by frankyma** 2020-11-04 23:47 UTC
Labels: bug, committed, priority 1
