### ISSUE TITLE
Project > Internship Engagement > Add Growth Plan > Getting "Post-upload action failed" error when an upload a file

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#723] opened 2021-02-12 12:18 UTC
**Roles:** All

**Describe the bug**
Project > Internship Engagement > Add Growth Plan > Getting `Post-upload action failed` error when an upload a file

**Steps to Reproduce**
1. Create Project (Internship)
2. Create Internship Engagement
3. Click on the `Add Growth Plan` button
4. Upload a new file

**Expected Result**
The file should be uploaded.

**Actual Result**
Getting `Post-upload action failed` error when an upload a file
See video - 

https://user-images.githubusercontent.com/5212585/107760112-4573e800-6d4f-11eb-9859-231b5a3f2628.mp4

cord-field# 093f2192

**Comment by CarsonF** [comment] 2021-02-12 17:36
Duplicate of https://github.com/SeedCompany/cord-api-v3/issues/1637

**Closed by CarsonF** 2021-02-12 17:36 UTC
